version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: strkv/foodgram_frontend
    volumes:
      - static:/app/result_build

  nginx:
    image: strkv/foodgram_gateway
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html/
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend

  backend:
    image: strkv/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
    depends_on:
      - db
