# Generated by Django 3.2 on 2023-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230824_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='qwe', upload_to='images'),
            preserve_default=False,
        ),
    ]
