# Generated by Django 3.2 on 2023-09-02 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(through='recipes.FavoriteRecipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
